[project]
name = "learning-operator"
version = "0.1.0"
description = "Aplikasi CLI pengenalan Operator Pada Python "
authors = [{name="Ahmad Hasan Maki", email="Hasanmaki.ahmad@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
    "sympy>=1.13.3",
]
